import 'dart:convert';

import 'package:dio/dio.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:portfolio/constants/constants.dart';
import 'package:portfolio/github/models/portfolio_data.dart';
import 'package:portfolio/profile/models/profile.dart';

/// Loads the app's two JSON documents.
///
/// Both follow the same rule: prefer the copy on raw.githubusercontent.com,
/// which is CDN-served, has no rate limit, and can be edited on `main` to
/// change the live site without a rebuild — then fall back to the copy bundled
/// as an asset when the network copy is unreachable.
///
/// `user_info.json` is regenerated by CI; `profile.json` is hand-edited.
class PortfolioDataSource {
  final Dio _dio;

  PortfolioDataSource({Dio? dio})
      : _dio = dio ??
            Dio(BaseOptions(
              connectTimeout: const Duration(seconds: 8),
              receiveTimeout: const Duration(seconds: 8),
              responseType: ResponseType.plain,
            ));

  Future<PortfolioData> fetchGithubData() async {
    final json = await _fetchJson(
      Constants.githubDataUrl,
      Constants.githubDataAsset,
    );
    return PortfolioData.fromJson(json);
  }

  Future<Profile> fetchProfile() async {
    final json = await _fetchJson(
      Constants.profileDataUrl,
      Constants.profileDataAsset,
    );
    return Profile.fromJson(json);
  }

  Future<Map<String, dynamic>> _fetchJson(
    String remoteUrl,
    String assetPath,
  ) async {
    try {
      final response = await _dio.get<String>(remoteUrl);
      final body = response.data;
      if (body != null && body.isNotEmpty) {
        return _decode(body);
      }
    } catch (_) {
      // Fall through to the bundled copy rather than showing an empty page.
    }

    return _decode(await rootBundle.loadString(assetPath));
  }

  Map<String, dynamic> _decode(String body) =>
      json.decode(body) as Map<String, dynamic>;
}
